# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [push]
default_install_hook_types: [pre-push, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: check-json
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 'e16741670e20fdfe2cb88f273a2ac177d820435b'
    hooks:
      - id: checkov
        args: [--quiet]
        language_version: python3.11
        files: .*
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '6fd1ced85fc139abd7f5ab4f3d78dab37592cd5e'
    hooks:
      - id: prettier
        stages: [commit, push]
# TODO: add this check once we have removed passwords from template yaml files
#- repo: https://github.com/Yelp/detect-secrets
#  rev: v1.2.0
#  hooks:
#    - id: detect-secrets
